import time
import pickle

args = [{'name': None,
         'mem': {(None, None): {'data': {},
                                'ctrl': []},
                 (True, None): {'data': {'t': None},
                                'ctrl': []},
                 (False, None): {'data': {'t': time.time(),
                                          'x': 1.0},
                                 'ctrl': [False, True]}},
         'exe': []},
        {'name': 'clock',
         'mem': {(None, None): None,
                 (True, 'time'): {'data': {'delta_t': 1.0},
                                  'ctrl': ['tick']},
                 (False, 'time'): {'data': {'t_dt': None},
                                   'ctrl': ['tock', 8601]}},
         'exe': [{'tag': 'clock.every',
                  'map': {'env': {'data': {},
                                  'ctrl': {'tick': True}}},
                  'key': {'env': [(None, None)],
                          'sys': [(True, 'time')],
                          'usr': [(False, 'time')]}},
                 {'tag': 'clock.iso8601',
                  'map': None,
                  'key': {'sys': [(None, None)],
                          'usr': [(False, 'time')]}}]},
        {'name': 'iss',
         'mem': {(None, None): None,
                 ('clock', 'time'): None,
                 (False, 2): {'data': {2: ['ISS (ZARYA)',
                                           '1 25544U 98067A   18184.80969102  .00001614  00000-0  31745-4 0  9993',
                                           '2 25544  51.6414 295.8524 0003435 262.6267 204.2868 15.54005638121106']},
                              'ctrl': []},
                 (True, 4): {'data': {4: None},
                             'ctrl': [4]},
                 (False, 'rec'): {'data': {'r_bar': None,
                                           'v_bar': None},
                                  'ctrl': ['rec']}},
         'exe': [{'tag': 'orb.tle2sgp',
                  'map': None,
                  'key': {'env': [(None, None)],
                          'tle': [(False, 2)],
                          'sgp': [(True, 4)]}},
                 {'tag': 'orb.sgp4tle',
                  'map': None,
                  'key': {'clk': [('clock', 'time')],
                          'sgp': [(True, 4)],
                          'orb': [(False, 'rec')]}}]},]
##        {'name': 'test',
##         'mem': {(None, None): None,
##                 (True, 'fun'): {'data': {'k': 1.0,
##                                          't': None,
##                                          'y': None,
##                                          'f': None},
##                                 'ctrl': ['i', 'o']},
##                 (False, 'sys'): {'data': {'y': 1.0},
##                                  'ctrl': ['ode']},
##                 (False, 'usr'): {'data': {'h': 0.25},
##                                  'ctrl': [True, False]}},
##         'exe': [{'tag': 'ode.euler',
##                  'map': None,
##                  'key': {'env': [(None, None)],
##                          'sys': [(False, 'sys')],
##                          'fun': [(True, 'fun')],
##                          'usr': [(False, 'usr')]}},
##                 {'tag': 'ode.exp',
##                  'map': None,
##                  'key': {'fun': [(True, 'fun')]}}]}]

if __name__ == '__main__':
    with open('test.pkl', 'wb') as pkl:
        pickle.dump(args, pkl)
