#!/bin/bash

python tps_auto_trend.py -z --sat-name=SkySat-2 \
    01-Library.ipynb \
    Anomalies.ipynb \
    Avionics.ipynb \
    EVR.ipynb \
    Exceptions.ipynb \
    GNC_Counters.ipynb \
    GNC_Gps.ipynb \
    GNC_Gyro.ipynb \
    GNC_Mag.ipynb \
    GNC_ReactionWheel.ipynb \
    GNC_StarTracker.ipynb \
    HDRS.ipynb \
    Image_Storage.ipynb \
    Orbit_TLE.ipynb \
    PES_NAND.ipynb \
    Power.ipynb \
    Radios.ipynb \
    Thermal.ipynb