- name: null
  items:
    ? !!python/tuple [true, null]
    : data:
        t: null
      ctrl: []
    ? !!python/tuple [false, null]
    : data:
        t: null
        x: null
      ctrl:
        - false
        - true
  procs: 
    - p: 100
      tag: .base@nop
      keys:
        param: !!python/tuple [false, null]
      maps: {}
